version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: sustainapal-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sustainapal
    restart: unless-stopped

volumes:
  mongodb_data: